/* 고객 */
CREATE TABLE shop.CUSTOMER (
	CUSTNO VARCHAR2(30) NOT NULL, /* 고객번호 */
	CUSTPW VARCHAR2(10) NOT NULL, /* 비밀번호 */
	CUSTNM VARCHAR2(30) NOT NULL, /* 고객명 */
	MOBILE VARCHAR2(20) NOT NULL, /* 전화번호 */
	ADDR VARCHAR2(50), /* 주소 */
	POINT NUMBER /* 마일리지 */
);

COMMENT ON TABLE shop.CUSTOMER IS '고객';

COMMENT ON COLUMN shop.CUSTOMER.CUSTNO IS '고객번호';

COMMENT ON COLUMN shop.CUSTOMER.CUSTPW IS '비밀번호';

COMMENT ON COLUMN shop.CUSTOMER.CUSTNM IS '고객명';

COMMENT ON COLUMN shop.CUSTOMER.MOBILE IS '전화번호';

COMMENT ON COLUMN shop.CUSTOMER.ADDR IS '주소';

COMMENT ON COLUMN shop.CUSTOMER.POINT IS '마일리지';

CREATE UNIQUE INDEX shop.PK_CUSTOMER
	ON shop.CUSTOMER (
		CUSTNO ASC
	);

ALTER TABLE shop.CUSTOMER
	ADD
		CONSTRAINT PK_CUSTOMER
		PRIMARY KEY (
			CUSTNO
		);

/* 창고 */
CREATE TABLE shop.WAREHOUSE (
	WHCD VARCHAR2(3) NOT NULL, /* 창고코드 */
	WH_LOC VARCHAR2(10) NOT NULL, /* 창고위치 */
	WH_ADDR VARCHAR2(100) /* 창고주소 */
);

COMMENT ON TABLE shop.WAREHOUSE IS '창고';

COMMENT ON COLUMN shop.WAREHOUSE.WHCD IS '창고코드';

COMMENT ON COLUMN shop.WAREHOUSE.WH_LOC IS '창고위치';

COMMENT ON COLUMN shop.WAREHOUSE.WH_ADDR IS '창고주소';

CREATE UNIQUE INDEX shop.PK_WAREHOUSE
	ON shop.WAREHOUSE (
		WHCD ASC
	);

ALTER TABLE shop.WAREHOUSE
	ADD
		CONSTRAINT PK_WAREHOUSE
		PRIMARY KEY (
			WHCD
		);

/* 주문 */
CREATE TABLE shop.ORD_TABLE (
	ORDNO NUMBER NOT NULL, /* 주문번호 */
	ORDDT DATE NOT NULL, /* 주문일자 */
	ITEMCD VARCHAR2(15) NOT NULL, /* 제품코드 */
	ITEM_QTY NUMBER NOT NULL, /* 수량 */
	CUSTNO VARCHAR2(30) NOT NULL, /* 고객번호 */
	ISDELIVERY CHAR(1) /* 배송여부 */
);

COMMENT ON TABLE shop.ORD_TABLE IS '주문';

COMMENT ON COLUMN shop.ORD_TABLE.ORDNO IS '주문번호';

COMMENT ON COLUMN shop.ORD_TABLE.ORDDT IS '주문일자';

COMMENT ON COLUMN shop.ORD_TABLE.ITEMCD IS '제품코드';

COMMENT ON COLUMN shop.ORD_TABLE.ITEM_QTY IS '수량';

COMMENT ON COLUMN shop.ORD_TABLE.CUSTNO IS '고객번호';

COMMENT ON COLUMN shop.ORD_TABLE.ISDELIVERY IS '배송여부';

CREATE UNIQUE INDEX shop.PK_ORD_TABLE
	ON shop.ORD_TABLE (
		ORDNO ASC
	);

ALTER TABLE shop.ORD_TABLE
	ADD
		CONSTRAINT PK_ORD_TABLE
		PRIMARY KEY (
			ORDNO
		);

/* 재고 */
CREATE TABLE shop.ITEM_BALANCE (
	ITEMCD VARCHAR2(15) NOT NULL, /* 제품코드 */
	WHCD VARCHAR2(3) NOT NULL, /* 창고코드 */
	OPEN_BALANCE NUMBER, /* 기초재고 */
	RECEIPT NUMBER, /* 입고 */
	ISSUE NUMBER /* 출고 */
);

COMMENT ON TABLE shop.ITEM_BALANCE IS '재고';

COMMENT ON COLUMN shop.ITEM_BALANCE.ITEMCD IS '제품코드';

COMMENT ON COLUMN shop.ITEM_BALANCE.WHCD IS '창고코드';

COMMENT ON COLUMN shop.ITEM_BALANCE.OPEN_BALANCE IS '기초재고';

COMMENT ON COLUMN shop.ITEM_BALANCE.RECEIPT IS '입고';

COMMENT ON COLUMN shop.ITEM_BALANCE.ISSUE IS '출고';

CREATE UNIQUE INDEX shop.PK_ITEM_BALANCE
	ON shop.ITEM_BALANCE (
		ITEMCD ASC,
		WHCD ASC
	);

ALTER TABLE shop.ITEM_BALANCE
	ADD
		CONSTRAINT PK_ITEM_BALANCE
		PRIMARY KEY (
			ITEMCD,
			WHCD
		);

/* 제품 */
CREATE TABLE shop.ITEM (
	ITEMCD VARCHAR2(15) NOT NULL, /* 제품코드 */
	ITEMNM VARCHAR2(20) NOT NULL, /* 제품명 */
	ITEM_DESC VARCHAR2(100), /* 제품상세명 */
	PRICE NUMBER, /* 제품가격 */
	COST NUMBER, /* 제품원가 */
	CATEGORY VARCHAR2(3) NOT NULL, /* 제품분류 */
	CLASS CHAR(1) NOT NULL /* 제품구분 */
);

COMMENT ON TABLE shop.ITEM IS '제품';

COMMENT ON COLUMN shop.ITEM.ITEMCD IS '제품코드';

COMMENT ON COLUMN shop.ITEM.ITEMNM IS '제품명';

COMMENT ON COLUMN shop.ITEM.ITEM_DESC IS '제품상세명';

COMMENT ON COLUMN shop.ITEM.PRICE IS '제품가격';

COMMENT ON COLUMN shop.ITEM.COST IS '제품원가';

COMMENT ON COLUMN shop.ITEM.CATEGORY IS '제품분류';

COMMENT ON COLUMN shop.ITEM.CLASS IS '제품구분';

CREATE UNIQUE INDEX shop.PK_ITEM
	ON shop.ITEM (
		ITEMCD ASC
	);

ALTER TABLE shop.ITEM
	ADD
		CONSTRAINT PK_ITEM
		PRIMARY KEY (
			ITEMCD
		);

/* 사원 */
CREATE TABLE shop.EMPLOYEES (
	EMP_NO NUMBER NOT NULL, /* 사원번호 */
	EMP_NAME VARCHAR2(20) NOT NULL, /* 사원이름 */
	EMP_TEL VARCHAR2(20) NOT NULL, /* 전화번호 */
	DEPTNO NUMBER NOT NULL, /* 부서번호 */
	ISADMIN CHAR(1) /* 관리자 */
);

COMMENT ON TABLE shop.EMPLOYEES IS '사원';

COMMENT ON COLUMN shop.EMPLOYEES.EMP_NO IS '사원번호';

COMMENT ON COLUMN shop.EMPLOYEES.EMP_NAME IS '사원이름';

COMMENT ON COLUMN shop.EMPLOYEES.EMP_TEL IS '전화번호';

COMMENT ON COLUMN shop.EMPLOYEES.DEPTNO IS '부서번호';

COMMENT ON COLUMN shop.EMPLOYEES.ISADMIN IS '관리자';

CREATE UNIQUE INDEX shop.PK_EMPLOYEES
	ON shop.EMPLOYEES (
		EMP_NO ASC
	);

ALTER TABLE shop.EMPLOYEES
	ADD
		CONSTRAINT PK_EMPLOYEES
		PRIMARY KEY (
			EMP_NO
		);

/* 부서 */
CREATE TABLE shop.DEPT (
	DEPTNO NUMBER NOT NULL, /* 부서번호 */
	DEPT_NAME VARCHAR2(20) NOT NULL /* 부서이름 */
);

COMMENT ON TABLE shop.DEPT IS '부서';

COMMENT ON COLUMN shop.DEPT.DEPTNO IS '부서번호';

COMMENT ON COLUMN shop.DEPT.DEPT_NAME IS '부서이름';

CREATE UNIQUE INDEX shop.PK_DEPT
	ON shop.DEPT (
		DEPTNO ASC
	);

ALTER TABLE shop.DEPT
	ADD
		CONSTRAINT PK_DEPT
		PRIMARY KEY (
			DEPTNO
		);

ALTER TABLE shop.ORD_TABLE
	ADD
		CONSTRAINT FK_CUSTOMER_TO_ORD_TABLE
		FOREIGN KEY (
			CUSTNO
		)
		REFERENCES shop.CUSTOMER (
			CUSTNO
		);

ALTER TABLE shop.ORD_TABLE
	ADD
		CONSTRAINT FK_ITEM_TO_ORD_TABLE
		FOREIGN KEY (
			ITEMCD
		)
		REFERENCES shop.ITEM (
			ITEMCD
		);

ALTER TABLE shop.ITEM_BALANCE
	ADD
		CONSTRAINT FK_ITEM_TO_ITEM_BALANCE
		FOREIGN KEY (
			ITEMCD
		)
		REFERENCES shop.ITEM (
			ITEMCD
		);

ALTER TABLE shop.ITEM_BALANCE
	ADD
		CONSTRAINT FK_WAREHOUSE_TO_ITEM_BALANCE
		FOREIGN KEY (
			WHCD
		)
		REFERENCES shop.WAREHOUSE (
			WHCD
		);

ALTER TABLE shop.EMPLOYEES
	ADD
		CONSTRAINT FK_DEPT_TO_EMPLOYEES
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES shop.DEPT (
			DEPTNO
		);