CREATE TABLE "CHECK_IN" (
  "CUSTNO" VARCHAR2(30 BYTE) NOT NULL,
  "ROOMNO" NUMBER NOT NULL,
  "C_CAPACITY" NUMBER NOT NULL,
  "CHECKIN_DT" DATE NOT NULL,
  "CHECKOUT_DT" DATE NOT NULL,
  CONSTRAINT "PK_CHECK_IN" PRIMARY KEY ("CUSTNO"),
  CONSTRAINT "SYS_C007187" CHECK ("CUSTNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007188" CHECK ("ROOMNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007189" CHECK ("C_CAPACITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007190" CHECK ("CHECKIN_DT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007191" CHECK ("CHECKOUT_DT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "CHECK_IN"."CUSTNO" IS '고객번호';
COMMENT ON COLUMN "CHECK_IN"."ROOMNO" IS '객실번호';
COMMENT ON COLUMN "CHECK_IN"."C_CAPACITY" IS '인원';
COMMENT ON COLUMN "CHECK_IN"."CHECKIN_DT" IS '체크인';
COMMENT ON COLUMN "CHECK_IN"."CHECKOUT_DT" IS '체크아웃';
COMMENT ON TABLE "CHECK_IN" IS '체크인';

CREATE TABLE "CHECK_OUT" (
  "CUSTNO" VARCHAR2(30 BYTE) NOT NULL,
  "ROOMNO" NUMBER NOT NULL,
  "CHECKOUT_DT" DATE NOT NULL,
  "C_CAPACITY" NUMBER NOT NULL,
  CONSTRAINT "PK_CHECK_OUT" PRIMARY KEY ("CUSTNO"),
  CONSTRAINT "SYS_C007193" CHECK ("CUSTNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007194" CHECK ("ROOMNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007195" CHECK ("CHECKOUT_DT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007196" CHECK ("C_CAPACITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "CHECK_OUT"."CUSTNO" IS '고객번호';
COMMENT ON COLUMN "CHECK_OUT"."ROOMNO" IS '객실번호';
COMMENT ON COLUMN "CHECK_OUT"."CHECKOUT_DT" IS '체크아웃';
COMMENT ON COLUMN "CHECK_OUT"."C_CAPACITY" IS '인원';
COMMENT ON TABLE "CHECK_OUT" IS '체크아웃';

CREATE TABLE "CUSTOMER" (
  "CUSTNO" VARCHAR2(30 BYTE) NOT NULL,
  "CUSTPW" VARCHAR2(20 BYTE) NOT NULL,
  "CUSTNM" VARCHAR2(30 BYTE) NOT NULL,
  "MOBILE" VARCHAR2(20 BYTE) NOT NULL,
  "EMAIL" VARCHAR2(50 BYTE) NOT NULL,
  "ADDR" VARCHAR2(50 BYTE),
  "GRADE" VARCHAR2(20 BYTE) NOT NULL,
  "POINT" NUMBER,
  CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CUSTNO"),
  CONSTRAINT "SYS_C007161" CHECK ("CUSTNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007162" CHECK ("CUSTPW" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007163" CHECK ("CUSTNM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007164" CHECK ("MOBILE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007165" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007166" CHECK ("GRADE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "CUSTOMER"."CUSTNO" IS '고객번호';
COMMENT ON COLUMN "CUSTOMER"."CUSTPW" IS '비밀번호';
COMMENT ON COLUMN "CUSTOMER"."CUSTNM" IS '이름';
COMMENT ON COLUMN "CUSTOMER"."MOBILE" IS '전화번호';
COMMENT ON COLUMN "CUSTOMER"."EMAIL" IS '이메일';
COMMENT ON COLUMN "CUSTOMER"."ADDR" IS '주소';
COMMENT ON COLUMN "CUSTOMER"."GRADE" IS '등급';
COMMENT ON COLUMN "CUSTOMER"."POINT" IS '마일리지';
COMMENT ON TABLE "CUSTOMER" IS '고객정보';

CREATE TABLE "DEPARTMENT" (
  "DEPTNO" NUMBER NOT NULL,
  "DNAME" VARCHAR2(20 BYTE) NOT NULL,
  "DEPTLOC" VARCHAR2(20 BYTE) NOT NULL,
  CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY ("DEPTNO"),
  CONSTRAINT "SYS_C007220" CHECK ("DEPTNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007221" CHECK ("DNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007222" CHECK ("DEPTLOC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "DEPARTMENT"."DEPTNO" IS '부서번호';
COMMENT ON COLUMN "DEPARTMENT"."DNAME" IS '부서이름';
COMMENT ON COLUMN "DEPARTMENT"."DEPTLOC" IS '부서위치';
COMMENT ON TABLE "DEPARTMENT" IS '부서';

CREATE TABLE "EMPLOYEE" (
  "EMPNO" NUMBER NOT NULL,
  "ENAME" VARCHAR2(30 BYTE) NOT NULL,
  "E_SEX" CHAR(1 BYTE) NOT NULL,
  "BIRTHDAY" DATE NOT NULL,
  "E_ADDR" VARCHAR2(50 BYTE),
  "E_MOBILE" VARCHAR2(30 BYTE) NOT NULL,
  "E_EMAIL" VARCHAR2(30 BYTE),
  "E_HIREDATE" DATE NOT NULL,
  "E_RESIGDATE" DATE,
  "E_SAL" NUMBER NOT NULL,
  "E_JOB" VARCHAR2(10 BYTE) NOT NULL,
  "DEPTNO" NUMBER NOT NULL,
  "MGRNO" NUMBER,
  CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY ("EMPNO"),
  CONSTRAINT "SYS_C007210" CHECK ("EMPNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007211" CHECK ("ENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007212" CHECK ("E_SEX" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007213" CHECK ("BIRTHDAY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007214" CHECK ("E_MOBILE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007215" CHECK ("E_HIREDATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007216" CHECK ("E_SAL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007217" CHECK ("E_JOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007218" CHECK ("DEPTNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "EMPLOYEE"."EMPNO" IS '직원번호';
COMMENT ON COLUMN "EMPLOYEE"."ENAME" IS '이름';
COMMENT ON COLUMN "EMPLOYEE"."E_SEX" IS '성별';
COMMENT ON COLUMN "EMPLOYEE"."BIRTHDAY" IS '생년월일';
COMMENT ON COLUMN "EMPLOYEE"."E_ADDR" IS '주소';
COMMENT ON COLUMN "EMPLOYEE"."E_MOBILE" IS '전화번호';
COMMENT ON COLUMN "EMPLOYEE"."E_EMAIL" IS '이메일';
COMMENT ON COLUMN "EMPLOYEE"."E_HIREDATE" IS '입사일';
COMMENT ON COLUMN "EMPLOYEE"."E_RESIGDATE" IS '퇴사일';
COMMENT ON COLUMN "EMPLOYEE"."E_SAL" IS '급여';
COMMENT ON COLUMN "EMPLOYEE"."E_JOB" IS '직급';
COMMENT ON COLUMN "EMPLOYEE"."DEPTNO" IS '부서번호';
COMMENT ON COLUMN "EMPLOYEE"."MGRNO" IS '관리자번호';
COMMENT ON TABLE "EMPLOYEE" IS '직원';

CREATE TABLE "FACILITY" (
  "FAC_NO" VARCHAR2(20 BYTE) NOT NULL,
  "FAC_NM" VARCHAR2(30 BYTE) NOT NULL,
  "FAC_STATUS" VARCHAR2(20 BYTE),
  "FAC_LOC" VARCHAR2(10 BYTE) NOT NULL,
  "RESVNO" VARCHAR2(30 BYTE),
  "ROOMNO" NUMBER,
  "FEEID" VARCHAR2(30 BYTE) NOT NULL,
  "FEE_AMT" NUMBER,
  "FAC_DESC" VARCHAR2(100 BYTE),
  CONSTRAINT "PK_FACILITY" PRIMARY KEY ("FAC_NO"),
  CONSTRAINT "SYS_C007205" CHECK ("FAC_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007206" CHECK ("FAC_NM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007207" CHECK ("FAC_LOC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007208" CHECK ("FEEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "FACILITY"."FAC_NO" IS '시설번호';
COMMENT ON COLUMN "FACILITY"."FAC_NM" IS '시설이름';
COMMENT ON COLUMN "FACILITY"."FAC_STATUS" IS '시설상태';
COMMENT ON COLUMN "FACILITY"."FAC_LOC" IS '시설위치';
COMMENT ON COLUMN "FACILITY"."RESVNO" IS '예약번호';
COMMENT ON COLUMN "FACILITY"."ROOMNO" IS '이용객실';
COMMENT ON COLUMN "FACILITY"."FEEID" IS '요금ID';
COMMENT ON COLUMN "FACILITY"."FEE_AMT" IS '요금';
COMMENT ON COLUMN "FACILITY"."FAC_DESC" IS '상세설명';
COMMENT ON TABLE "FACILITY" IS '부대시설';

CREATE TABLE "PAYMENT" (
  "PYM_ID" VARCHAR2(30 BYTE) NOT NULL,
  "RESVNO" VARCHAR2(30 BYTE) NOT NULL,
  "PYM_STATUS" VARCHAR2(10 BYTE),
  "PYM_AMT" NUMBER,
  "PYM_DT" DATE,
  "PYM_MTD" VARCHAR2(10 BYTE),
  CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PYM_ID"),
  CONSTRAINT "SYS_C007202" CHECK ("PYM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007203" CHECK ("RESVNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "PAYMENT"."PYM_ID" IS '결제ID';
COMMENT ON COLUMN "PAYMENT"."RESVNO" IS '예약번호';
COMMENT ON COLUMN "PAYMENT"."PYM_STATUS" IS '결제상태';
COMMENT ON COLUMN "PAYMENT"."PYM_AMT" IS '결제금액';
COMMENT ON COLUMN "PAYMENT"."PYM_DT" IS '결제일자';
COMMENT ON COLUMN "PAYMENT"."PYM_MTD" IS '결제수단';
COMMENT ON TABLE "PAYMENT" IS '결제';

CREATE TABLE "RATE" (
  "FEEID" VARCHAR2(30 BYTE) NOT NULL,
  "FEE_AMT" NUMBER,
  "ROOMTYPE" VARCHAR2(20 BYTE) NOT NULL,
  "NOP" NUMBER,
  "F_SEASON" VARCHAR2(10 BYTE) NOT NULL,
  "STARTDT" DATE,
  "ENDDT" DATE,
  CONSTRAINT "PK_RATE" PRIMARY KEY ("FEEID"),
  CONSTRAINT "SYS_C007198" CHECK ("FEEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007199" CHECK ("ROOMTYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007200" CHECK ("F_SEASON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "RATE"."FEEID" IS '요금ID';
COMMENT ON COLUMN "RATE"."FEE_AMT" IS '요금';
COMMENT ON COLUMN "RATE"."ROOMTYPE" IS '객실유형';
COMMENT ON COLUMN "RATE"."NOP" IS '인원';
COMMENT ON COLUMN "RATE"."F_SEASON" IS '시즌';
COMMENT ON COLUMN "RATE"."STARTDT" IS '시작일';
COMMENT ON COLUMN "RATE"."ENDDT" IS '종료일';
COMMENT ON TABLE "RATE" IS '요금';

CREATE TABLE "RESERVATION" (
  "RESVNO" VARCHAR2(30 BYTE) NOT NULL,
  "CUSTNO" VARCHAR2(30 BYTE) NOT NULL,
  "ROOMNO" NUMBER NOT NULL,
  "RESVDT" DATE NOT NULL,
  "CHECKIN_DT" DATE NOT NULL,
  "CHECKOUT_DT" DATE NOT NULL,
  "R_CAPACITY" NUMBER NOT NULL,
  "R_COMMENT" VARCHAR2(100 BYTE),
  "ISPAID" CHAR(1 BYTE) NOT NULL,
  "FEEID" VARCHAR2(30 BYTE) NOT NULL,
  CONSTRAINT "PK_RESERVATION" PRIMARY KEY ("RESVNO"),
  CONSTRAINT "SYS_C007174" CHECK ("RESVNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007175" CHECK ("CUSTNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007176" CHECK ("ROOMNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007177" CHECK ("RESVDT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007178" CHECK ("CHECKIN_DT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007179" CHECK ("CHECKOUT_DT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007180" CHECK ("R_CAPACITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007181" CHECK ("ISPAID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007182" CHECK ("FEEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "RESERVATION"."RESVNO" IS '예약번호';
COMMENT ON COLUMN "RESERVATION"."CUSTNO" IS '고객번호';
COMMENT ON COLUMN "RESERVATION"."ROOMNO" IS '객실번호';
COMMENT ON COLUMN "RESERVATION"."RESVDT" IS '예약일';
COMMENT ON COLUMN "RESERVATION"."CHECKIN_DT" IS '체크인';
COMMENT ON COLUMN "RESERVATION"."CHECKOUT_DT" IS '체크아웃';
COMMENT ON COLUMN "RESERVATION"."R_CAPACITY" IS '인원';
COMMENT ON COLUMN "RESERVATION"."R_COMMENT" IS '전달사항';
COMMENT ON COLUMN "RESERVATION"."ISPAID" IS '결제여부';
COMMENT ON COLUMN "RESERVATION"."FEEID" IS '요금ID';
COMMENT ON TABLE "RESERVATION" IS '예약정보';

CREATE TABLE "ROOM" (
  "ROOMNO" NUMBER NOT NULL,
  "FEEID" VARCHAR2(30 BYTE) NOT NULL,
  "FEE_AMT" NUMBER,
  "ROOMTYPE" VARCHAR2(20 BYTE) NOT NULL,
  "RM_CAPACITY" NUMBER NOT NULL,
  "ROOM_STATUS" VARCHAR2(20 BYTE) NOT NULL,
  "ROOM_DESC" VARCHAR2(100 BYTE),
  CONSTRAINT "PK_ROOM" PRIMARY KEY ("ROOMNO"),
  CONSTRAINT "SYS_C007168" CHECK ("ROOMNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007169" CHECK ("FEEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007170" CHECK ("ROOMTYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007171" CHECK ("RM_CAPACITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007172" CHECK ("ROOM_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "ROOM"."ROOMNO" IS '객실번호';
COMMENT ON COLUMN "ROOM"."FEEID" IS '요금ID';
COMMENT ON COLUMN "ROOM"."FEE_AMT" IS '요금';
COMMENT ON COLUMN "ROOM"."ROOMTYPE" IS '객실유형';
COMMENT ON COLUMN "ROOM"."RM_CAPACITY" IS '수용인원';
COMMENT ON COLUMN "ROOM"."ROOM_STATUS" IS '객실상태';
COMMENT ON COLUMN "ROOM"."ROOM_DESC" IS '상세설명';
COMMENT ON TABLE "ROOM" IS '객실정보';

CREATE TABLE "ROOM_STATUS" (
  "ROOMNO" NUMBER NOT NULL,
  "RS_DATE" DATE,
  "ROOM_STATUS" VARCHAR2(10 BYTE) NOT NULL,
  CONSTRAINT "PK_ROOM_STATUS" PRIMARY KEY ("ROOMNO"),
  CONSTRAINT "SYS_C007184" CHECK ("ROOMNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE,
  CONSTRAINT "SYS_C007185" CHECK ("ROOM_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "ROOM_STATUS"."ROOMNO" IS '객실번호';
COMMENT ON COLUMN "ROOM_STATUS"."RS_DATE" IS '날짜';
COMMENT ON COLUMN "ROOM_STATUS"."ROOM_STATUS" IS '객실상태';
COMMENT ON TABLE "ROOM_STATUS" IS '객실상태';

ALTER TABLE "CHECK_IN" ADD CONSTRAINT "FK_CUSTOMER_TO_CHECK_IN" FOREIGN KEY ("CUSTNO") REFERENCES "CUSTOMER" ("CUSTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CHECK_IN" ADD CONSTRAINT "FK_ROOM_TO_CHECK_IN" FOREIGN KEY ("ROOMNO") REFERENCES "ROOM" ("ROOMNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CHECK_OUT" ADD CONSTRAINT "FK_CHECK_IN_TO_CHECK_OUT" FOREIGN KEY ("CUSTNO") REFERENCES "CHECK_IN" ("CUSTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CHECK_OUT" ADD CONSTRAINT "FK_CUSTOMER_TO_CHECK_OUT" FOREIGN KEY ("CUSTNO") REFERENCES "CUSTOMER" ("CUSTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "CHECK_OUT" ADD CONSTRAINT "FK_ROOM_TO_CHECK_OUT" FOREIGN KEY ("ROOMNO") REFERENCES "ROOM" ("ROOMNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_DEPARTMENT_TO_EMPLOYEE" FOREIGN KEY ("DEPTNO") REFERENCES "DEPARTMENT" ("DEPTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FACILITY" ADD CONSTRAINT "FK_RATE_TO_FACILITY" FOREIGN KEY ("FEEID") REFERENCES "RATE" ("FEEID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FACILITY" ADD CONSTRAINT "FK_RESERVATION_TO_FACILITY" FOREIGN KEY ("RESVNO") REFERENCES "RESERVATION" ("RESVNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_RESERVATION_TO_PAYMENT" FOREIGN KEY ("RESVNO") REFERENCES "RESERVATION" ("RESVNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_CHECK_IN_TO_RESERVATION" FOREIGN KEY ("CUSTNO") REFERENCES "CHECK_IN" ("CUSTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_CHECK_OUT_TO_RESERVATION" FOREIGN KEY ("CUSTNO") REFERENCES "CHECK_OUT" ("CUSTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_CUSTOMER_TO_RESERVATION" FOREIGN KEY ("CUSTNO") REFERENCES "CUSTOMER" ("CUSTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_RATE_TO_RESERVATION" FOREIGN KEY ("FEEID") REFERENCES "RATE" ("FEEID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_ROOM_TO_RESERVATION" FOREIGN KEY ("ROOMNO") REFERENCES "ROOM" ("ROOMNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOM" ADD CONSTRAINT "FK_RATE_TO_ROOM" FOREIGN KEY ("FEEID") REFERENCES "RATE" ("FEEID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ROOM" ADD CONSTRAINT "FK_ROOM_STATUS_TO_ROOM" FOREIGN KEY ("ROOMNO") REFERENCES "ROOM_STATUS" ("ROOMNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

